version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      SECRET_KEY: =*njxxx%fjvcwardqah7ue#3xo7&7ff+$$-ls@w&l87*rw1if)g
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
